### ISSUE TITLE
使用 GitHub issue 作为评论插件

### ISSUE THREAD

**Issue by billryan** [billryan/blog#1]
https://github.com/gitalk/gitalk

使用 GitHub issue 作为评论存储，GitHub 用户登录，挺有意思的

**Comment by billryan** [comment]
存在严重的安全问题 https://github.com/gitalk/gitalk/issues/95

**Comment by billryan** [comment]
源文件 https://github.com/billryan/blog/blob/master/posts/2018-02/2018-02-23_23-19-29.md

**Comment by billryan** [comment]
[source](../blob/master/posts/2018-02/2018-02-23_23-19-29.md)

**Comment by billryan** [comment]
评论页模板 #10

**Comment by billryan** [comment]
DONE https://github.com/billryan/gitbook-plugin-ghcomment

**Comment by billryan** [comment]
对 gitbook change 的状态切换存在 bug, 需要参考 plugin-disqus 的设计

**Comment by billryan** [comment]
Fixed with comment and migrated to Hugo

https://github.com/billryan/hugo-theme-even

**Comment by Zyuhang** [comment]
> 完成https://github.com/billryan/gitbook-plugin-ghcomment

11

**Comment by Zyuhang** [comment]
> 已修正问题并已迁移至雨果
> 
> https://github.com/billryan/hugo-theme-even

Duplicate of #22
