### ISSUE TITLE
CICD

### ISSUE THREAD

**Issue by billryan** [billryan/blog#3]
持续集成，达到更新 markdown 即可更新静态网页的效果

**Comment by billryan** [comment]
- [x] 使用 travis 编译
- [x] 使用 travis 部署至 GitHub release(备份)
- [ ] 使用 travis 部署至 gh-pages 分支
- [ ] 从 VPS 迁移至 Pages 服务，强制转向 HTTPS

**Comment by at15** [comment]
感觉用 netlify 比 gh pages 好一些 https://zhuanlan.zhihu.com/p/31416527

**Comment by billryan** [comment]
看了下你们的介绍，netlify 确实不错，相比于注重通用 CI 用途的 travis 而言对 Web 项目更为友好，能够自定义 URL 访问不同的构建结果这个特性很适合多人投稿的模式，另一个文档项目下周末有空玩一玩 netlify, 多谢推荐！
